### ISSUE TITLE
Bitte um Korrektur

### ISSUE THREAD

**Issue by DerAlexx** [DerAlexx/Haskell-Aufgabe-1#1]
Sehr geehrter Herr Güdemann,

wie in der Aufgabe am Ende beschrieben habe ich Sie in dieser Issue zu meinem Projekt assigned.

Mit freundlichen Grüßen.

**Comment by mgudemann** [comment]
Die Property ist so nicht ganz richtig. Was getestet werden soll, ist dass für alle `a`, `b`, `ggT a b` der Funktion `gcd a b` entspricht, die schon in der Haskell Standard Bibliothek ist.

**Comment by DerAlexx** [comment]
Achso entschuldigung da hab ich die Aufgabe missverstanden. Ich hoffe jetzt passt das.

**Comment by mgudemann** [comment]
sieht gut aus

**Comment by DerAlexx** [comment]
Alles klar vielen Dank für Ihre Zeit und Mühe.
